# Generated by Selenium IDE

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginNegativo():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.implicitly_wait(10)
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginNegativo(self):
    self.driver.get("https://www.giulianaflores.com.br/")
    self.driver.set_window_size(1440, 807)
    element = self.driver.find_element(By.CSS_SELECTOR, ".swiper-slide-active .img_banner")
   
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    
   
    self.driver.find_element(By.CSS_SELECTOR, "#perfil-hidden > img").click()
    self.driver.find_element(By.CSS_SELECTOR, "#UrlLogin > a").click()
    
    self.driver.find_element(By.ID, "ContentSite_txtEmail").click()
    self.driver.find_element(By.ID, "ContentSite_txtEmail").send_keys("vinicius.manuel.dasilva@icloud.com")
    
    self.driver.find_element(By.ID, "ContentSite_txtPassword").click()
    self.driver.find_element(By.ID, "ContentSite_txtPassword").send_keys("ujh")
    
    self.driver.find_element(By.ID, "ContentSite_ibtContinue").click()
    
    self.driver.find_element(By.ID, "ContentSite_txtPassword").click()
    self.driver.find_element(By.ID, "ContentSite_txtPassword").send_keys("ujh")
    
    self.driver.find_element(By.ID, "adopt-accept-all-button").click()
    
    time.sleep(10)
    
    self.driver.find_element(By.ID, "ContentSite_ibtContinue").click()
  

